// Row collection and output. Every row is validated against `schema.ts` as it is
// added, so a malformed fact is an extractor crash naming the relation and the
// row — never a table the engine half-imports.

import * as fs from "node:fs";
import * as path from "node:path";
import { LAYERS, RELATION_BY_NAME, RELATIONS, type Column, type Layer, type Relation } from "./schema.ts";

export type Cell = string | number | boolean | null;
export type Row = Record<string, Cell | undefined>;

const IDENT = /^[a-z][A-Za-z0-9_]*$/;
// §3's reserved words: a symbol cell spelled like one would read back as the keyword.
const RESERVED = new Set(["import", "as", "declare", "not", "true", "false", "absent", "is"]);
const TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/;

export class Tables {
  private readonly data = new Map<string, Cell[][]>();

  add(relation: string, row: Row): void {
    const rel = RELATION_BY_NAME.get(relation);
    if (rel === undefined) throw new Error(`code-facts: no relation named \`${relation}\` in schema.ts`);
    for (const key of Object.keys(row)) {
      if (!rel.columns.some((c) => c.name === key)) {
        throw new Error(`code-facts: \`${relation}\` has no column \`${key}\` (row ${JSON.stringify(row)})`);
      }
    }
    const cells: Cell[] = rel.columns.map((column) => checkCell(rel, column, row[column.name], row));
    let rows = this.data.get(relation);
    if (rows === undefined) {
      rows = [];
      this.data.set(relation, rows);
    }
    rows.push(cells);
  }

  /** Rows of a relation as objects — for tests and in-process consumers. */
  rows(relation: string): Row[] {
    const rel = RELATION_BY_NAME.get(relation);
    if (rel === undefined) throw new Error(`code-facts: no relation named \`${relation}\``);
    return (this.data.get(relation) ?? []).map((cells) => {
      const obj: Row = {};
      rel.columns.forEach((c, i) => {
        obj[c.name] = cells[i] ?? null;
      });
      return obj;
    });
  }

  count(relation: string): number {
    return this.data.get(relation)?.length ?? 0;
  }

  /** Drops exact duplicate rows, keeping first occurrences in order. */
  dedupe(): void {
    for (const [name, rows] of this.data) {
      const seen = new Set<string>();
      const kept: Cell[][] = [];
      for (const r of rows) {
        const key = JSON.stringify(r);
        if (seen.has(key)) continue;
        seen.add(key);
        kept.push(r);
      }
      this.data.set(name, kept);
    }
  }

  /** Writes `facts/`, `schema/`, `lib/` and `SCHEMA.md` under `outDir`. */
  write(outDir: string, layers: ReadonlySet<Layer>, libDir: string): void {
    fs.mkdirSync(outDir, { recursive: true });
    const factsDir = path.join(outDir, "facts");
    const schemaDir = path.join(outDir, "schema");
    fs.rmSync(factsDir, { recursive: true, force: true });
    fs.rmSync(schemaDir, { recursive: true, force: true });
    fs.mkdirSync(factsDir);
    fs.mkdirSync(schemaDir);

    const written = RELATIONS.filter((r) => layers.has(r.layer));
    // relation_rows describes every relation written, itself included.
    this.data.delete("relation_rows");
    for (const r of written) {
      const n = r.name === "relation_rows" ? written.length : this.count(r.name);
      this.add("relation_rows", { relation: r.name, layer: r.layer, rows: n });
    }

    for (const r of written) {
      const rows = this.data.get(r.name) ?? [];
      // An empty table is an empty file: under the explicit schema the import
      // declares, that is exactly the empty relation.
      const fd = fs.openSync(path.join(factsDir, `${r.name}.jsonl`), "w");
      try {
        let buf = "";
        for (const cells of rows) {
          const obj: Record<string, Cell> = {};
          r.columns.forEach((c, i) => {
            obj[c.name] = cells[i] ?? null;
          });
          buf += `${JSON.stringify(obj)}\n`;
          if (buf.length > 1 << 20) {
            fs.writeSync(fd, buf);
            buf = "";
          }
        }
        fs.writeSync(fd, buf);
      } finally {
        fs.closeSync(fd);
      }
    }

    for (const layer of LAYERS) {
      fs.writeFileSync(path.join(schemaDir, `${layer}.dl`), layerSchema(layer, layers.has(layer), this));
    }
    fs.writeFileSync(
      path.join(schemaDir, "all.dl"),
      [
        "% Generated by code-facts. Imports every layer — convenient, but an analysis",
        "% is cheaper importing only the layer (or lib/*.dl) it needs. A layer that was",
        "% not extracted is imported too: its relations are declared and empty, so a",
        "% program written against the whole schema still runs on a partial extraction.",
        ...LAYERS.map((l) => `import "${l}.dl".`),
        "",
      ].join("\n"),
    );

    const libOut = path.join(outDir, "lib");
    fs.rmSync(libOut, { recursive: true, force: true });
    fs.mkdirSync(libOut);
    for (const f of fs.readdirSync(libDir).sort()) {
      if (f.endsWith(".dl")) fs.copyFileSync(path.join(libDir, f), path.join(libOut, f));
    }

    fs.writeFileSync(path.join(outDir, "SCHEMA.md"), schemaMarkdown(layers, this));
  }
}

function checkCell(rel: Relation, column: Column, value: Cell | undefined, row: Row): Cell {
  const where = () => `\`${rel.name}.${column.name}\` in ${JSON.stringify(row)}`;
  if (value === undefined || value === null) {
    if (column.nullable === true) return null;
    throw new Error(`code-facts: ${where()} is missing and the column is not nullable`);
  }
  switch (column.type) {
    case "string":
      if (typeof value !== "string") throw new Error(`code-facts: ${where()} must be a string`);
      // A lone UTF-16 surrogate (a test fixture's "\uD800", say) has no UTF-8
      // form; the reader rejects its JSON escape, so it becomes U+FFFD here.
      return value.toWellFormed();
    case "int":
      if (typeof value !== "number" || !Number.isSafeInteger(value)) throw new Error(`code-facts: ${where()} must be an integer`);
      return value;
    case "bool":
      if (typeof value !== "boolean") throw new Error(`code-facts: ${where()} must be a boolean`);
      return value;
    case "symbol":
      if (typeof value !== "string" || !IDENT.test(value) || RESERVED.has(value)) {
        throw new Error(`code-facts: ${where()} must be a lowercase identifier that is not a reserved word`);
      }
      if (column.values !== undefined && !column.values.includes(value)) {
        throw new Error(`code-facts: ${where()} must be one of ${column.values.join(", ")}`);
      }
      return value;
    case "timestamp":
      if (typeof value !== "string" || !TIMESTAMP.test(value)) throw new Error(`code-facts: ${where()} must be YYYY-MM-DDTHH:MM:SS`);
      return value;
  }
}

function layerSchema(layer: Layer, extracted: boolean, tables: Tables): string {
  const lines = [`% Generated by code-facts — the \`${layer}\` layer.`];
  if (!extracted) {
    lines.push("% NOT EXTRACTED in this run (switched off with --layers / --no-git).");
    lines.push("% Declared but empty, so a rule over these relations is well-formed and");
    lines.push("% derives nothing. Without the declarations it is a *semantic error*: a");
    lines.push("% named argument needs a known field name, so `lib/checks.dl` — which");
    lines.push("% covers every layer — would not run at all on a partial extraction, which");
    lines.push("% is exactly what a large repository needs (found dogfooding, 2026-09-12).");
    for (const r of RELATIONS.filter((x) => x.layer === layer)) {
      const cols = r.columns.map((c) => `${c.name}: ${c.type}`).join(", ");
      lines.push(`declare ${r.name}(${cols}).`);
    }
    return `${lines.join("\n")}\n`;
  }
  lines.push("% Column documentation: ../SCHEMA.md. Types are explicit so an empty or");
  lines.push("% all-absent column still has one; `symbol` columns are written bare: kind: class.");
  for (const r of RELATIONS.filter((x) => x.layer === layer)) {
    const n = tables.count(r.name);
    lines.push("");
    lines.push(`% ${r.name} — ${n} row${n === 1 ? "" : "s"}. ${r.doc}`);
    const cols = r.columns.map((c) => `${c.name}: ${c.type}`).join(", ");
    lines.push(`import "../facts/${r.name}.jsonl" as ${r.name}(${cols}).`);
  }
  return `${lines.join("\n")}\n`;
}

function schemaMarkdown(layers: ReadonlySet<Layer>, tables: Tables): string {
  const out: string[] = [
    "# code-facts schema",
    "",
    "Generated from `src/schema.ts`. Import `schema/<layer>.dl` (or `schema/all.dl`), or a",
    "rule library in `lib/`, which imports the schema it needs.",
    "",
  ];
  for (const layer of LAYERS) {
    out.push(`## ${layer}${layers.has(layer) ? "" : " (not extracted in this run)"}`, "");
    for (const r of RELATIONS.filter((x) => x.layer === layer)) {
      out.push(`### \`${r.name}\` — ${tables.count(r.name)} rows`, "", r.doc, "");
      out.push("| column | type | meaning |", "|---|---|---|");
      for (const c of r.columns) {
        const type = `${c.type}${c.nullable === true ? "?" : ""}`;
        const values = c.values !== undefined ? ` — one of ${c.values.map((v) => `\`${v}\``).join(", ")}` : "";
        out.push(`| \`${c.name}\` | ${type} | ${c.doc.replaceAll("|", "\\|")}${values} |`);
      }
      out.push("");
    }
  }
  return out.join("\n");
}
